### ISSUE TITLE
Setting `$VERBOSE` to `true` causes infinite warning output loop 

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/solar-north#4]
**Setting `$VERBOSE` to true causes infinite warning output loop and the Ruby Console is unusable.**

```ruby
"#{ENV["AppData"]}/SketchUp/SketchUp 2021/SketchUp/Plugins/su_solarnorth/generic_tool.rb:29: warning:
 instance variable @active_tool not initialized"
```

The console continues to spit out the warning until `$VERBOSE` is set `false` again.

This likely means that the source is a validation proc for a toolbar button.

**Comment by Eneroth3** [comment]
Added a fix for this.

Not sure if this is enough to make an EW update for or if we should wait until there are more changes to the extension.

**Comment by thomthom** [comment]
I don't foresee any additional changes in the nearby future. Lets just push the update.
