### ISSUE TITLE
Sometimes this doesn't work with SketchUp 2024. Not sure why though.

### ISSUE THREAD

**Issue by a4jp-com** [SketchUp/solar-north#5]
Sometimes this doesn't work with SketchUp. Could there be a bug or do you think the problem is in SketchUp?

**Comment by a4jp-com** [comment]
SketchUp 2024 uses Ruby 3.2.2.
SketchUp 2023.0.2 uses Ruby to 2.7.7.
Does this just need to be recompiled?

**Comment by Eneroth3** [comment]
Hi,

Could you elaborate what isn't working? What exactly are you trying to do and what happens instead?

**Comment by a4jp-com** [comment]
I tried loading the extension on a few computers but the pallet with icons didn't show up. Then after opening a few different projects it just started working. I'm not sure what happened but it might have a bug. The website also needs an update. It is working with 2024 all besides that.

**Comment by thomthom** [comment]
* Is the extension listed in Extension Manager, showing as enabled?
* Do you see the toolbar listed under the list of toolbars SketchUp knows about?
* Windows or macOS?

**Comment by a4jp-com** [comment]
Windows 11. But everything is okay now. It's in the menu and the icons are showing as well. Not sure what happened before though.
